name: archi_connect
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^4.2.1
  avatar_glow: ^2.0.2
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  image_picker: ^0.7.2+1
  google_fonts: ^3.0.1
  curved_navigation_bar: ^1.0.3
  flex_color_scheme: ^6.1.2
  equatable: ^2.0.5
  flutter_spinkit: ^5.1.0
  flash: ^2.0.5
  url_launcher: ^6.1.7
  pie_chart: ^5.3.2
  flutter_rating_stars: ^1.0.3+4
  flutter_staggered_animations: ^1.1.1
  flutter_appauth: ^4.2.1
  salomon_bottom_bar: ^3.3.1
  provider: ^6.0.5
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/eiffel-tower.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/configs/
